# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.

on:
  schedule:
    - cron: "*/1 * * * *"

# This command allows us to run the Action automatically from the Actions tab.
workflow_dispatch:

# The sequence of runs in this workflow:
jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: Platane/snk@master
        with:
          github_user_name: hubeen
          gif_out_path: dist/hubeen-grid-snake.gif
          svg_out_path: dist/hubeen-grid-snake.svg
          
      - run: git status
